---
- name: Set hostname {{ inventory_hostname }}
  become: True
  hostname: name={{inventory_hostname}}
  when: ansible_nodename not in groups['region']

- name: Add hostname to /etc/hosts
  become: True
  lineinfile: dest='/etc/hosts' line='127.0.0.1   {{inventory_hostname}}'

- name: Unsetting env variables
  become: True
  lineinfile: >
        line='{{item}}'
        dest=/etc/bashrc
        state=present
        create=yes
  with_items:
    - 'unset PROMPT_COMMAND'

- name: Installing epel repo
  become: yes
  yum:  name="epel-release" state=latest

- name: Install packages
  become: yes
  yum:  name={{ item }} state=latest
  with_items:
      - net-tools
      - iptraf
      - libselinux-python
      - vim
      - telnet
      - wget
      - mc
      - htop
      - screen
      - mlocate
      - nano
      - git
      - python-setuptools
      - python-pip
  ignore_errors: yes
...