---
- name: restart_service
  service: >
    name=tinc@{{connection.name}}
    state=restarted
  when: ansible_os_family == "RedHat"

- name: restart_service
  become: True
  service:
    name: tinc
    state: restarted
  when: ansible_os_family == "Debian"
