---
  - name: restart_service
    become: True
    service: >
        name=tinc@{{connection.name}}
        state=restarted
#    shell: tincd -n {{connection.name}} -k; wait; tincd -n {{connection.name}}
...
