# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
    config.vm.box = "bento/centos-7.3"
    config.vm.hostname = "SeedAI"
    config.ssh.insert_key = false
    config.ssh.forward_agent = true

    config.vm.provider "virtualbox" do |vb|
        vb.memory = "2048"
        vb.cpus = 2
    end
    config.vm.define "dev_seed_app_01", primary: true do |dev_seed_app_01|
        dev_seed_app_01.vm.network "private_network", ip: "192.168.100.20"
    end
end